### ISSUE TITLE
Suggestion - put website link here

### ISSUE THREAD

**Issue by mathemakitten** [TDLS/tdls.github.io#39]
Hi! I would recommend adding the link to https://tdls.a-i.science somewhere prominent on this repo (like on the main markdown). A Google search for TDLS doesn't yet return the a-i.science website, and it might help with SEO for people to understand where this website goes. 

(hopefully this will encourage other people to get more involved with this Git repo also :))

**Comment by settinghead** [comment]
Thanks for the suggestion. It's at the top of the README.md now. :)
